openapi: '3.0.0'
info:
  description: " Yuvajunction - transaction service
  
  
  
  That API use:
  
  
 
  
  **ChangeLog**
  
  |Version|Release|Delivery Sprint|Impacts                    |Type    |Note|
  
  |-----|---------|----|--------------------------------------|-----------|-|
  
  |1.0.0|   |-   |**Initial version**                   |           | | 
    
  
  
  "
  version: 1.0.0
  title: Transaction API
 
 
    
paths:
  /document/{documentId}:
    get:
      tags:
      - Get Document details
      summary: "The service get a document metadata from the database."
      description: This service is called when a document metadata is to be retrived by its id.
      operationId: "get"
      parameters:
        - in: path
          required: true
          name: documentId
          schema:
            type: string
            
              
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
        '400':
          description: Business Exception
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'
        '500':
          description: Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'       
      security:
      - basicAuth: []
      
  /document:
    post:
      tags:
      - Create Document
      summary: "The service creates a new document  in the database."
      description: This service is called when a new document metada is crated. It will take the relevant document information as input and create a new item in document table.
      operationId: "create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDocumentRequest' 
              
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponse"
        '400':
          description: Business Exception
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'
        '500':
          description: Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'       
      security:
      - basicAuth: []
components:  
  schemas:
    DocumentResponse:
      allOf:
        - type: object
          properties:
            id: 
              type: string
            documentType:
              type: string
              enum: [RentalAgreement,Others]   
            creationDate:
              type: string
              format: date-time
            location:
              type: string
              format: uri
          
    CreateDocumentRequest:
      allOf:
        - type: object
          properties:
            location:
              type: string
            documentType:
              type: string
              enum: [RentalAgreement,Others]
            
    
    ExecuteException:
      type: object
      properties:
        code:
          type: string
          description: The code identifying the type of error
        message:
          type: string
          description: The error message
