openapi: '3.0.0'
info:
  description: " Yuvajunction - Party service
  
  
  
  That API use:
  
  
 
  
  **ChangeLog**
  
  |Version|Release|Delivery Sprint|Impacts                    |Type    |Note|
  
  |-----|---------|----|--------------------------------------|-----------|-|
  
  |1.0.0|   |-   |**Initial version**                   |           | | 
    
  
  
  "
  version: 1.0.0
  title: Party API
  
servers:
  - url: /party  
paths:
  /{partyId}:
    get:
      tags:
      - Get Party details
      summary: "The service get a Party detail from the database."
      description: This service is called when a party details is to be retrived by its id.
      operationId: "get"
      parameters:
        - in: path
          required: true
          name: partyId
          schema:
            type: string
            
              
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartyResponse"
        '400':
          description: Business Exception
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'
        '500':
          description: Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'       
      security:
      - basicAuth: []
  /:
    post:
      tags:
      - Create Party
      summary: "The service creates a new Party item in the database."
      description: This service is called when a new party is registered. It will take the relevant paty infrmation as input and create a new item in Party table.
      operationId: "create"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePartyRequest' 
              
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePartyResponse"
        '400':
          description: Business Exception
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'
        '500':
          description: Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'       
      security:
      - basicAuth: []
      
  /search:
    post:
      tags:
      - Seach Parties
      summary: "The service retrives Party items from the database based on the search criteria."
      description: This service is called when a party is searched. It will take the relevant paty infrmation as input and retrives all parties maching the input.
      operationId: "search"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPartyRequest' 
              
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchPartyResponse"
        '400':
          description: Business Exception
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'
        '500':
          description: Server Error
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ExecuteException'       
      security:
      - basicAuth: []    
components:  
  schemas:
    PartyDemographics:
      type: object
      description: party demographics  
      properties:
        firstName:
          type: string
        middleName:
          type: string
        lastName:
          type: string
        dob:
          type: string
    PartyResponse:
      allOf:
        - type: object
          properties:
            id: 
              type: string
        - $ref: '#/components/schemas/PartyDemographics'
        - type: object
          properties:
            addresses:
              type: array
              items:
                $ref: '#/components/schemas/PartyAddress'
            contacts:
              type: array
              items:
                $ref: '#/components/schemas/PartyContact'
            properties:
              type: array
              items:
                $ref: '#/components/schemas/PartyProperty'
          
    PartyContact:
      anyOf:
        - type: object
          description: email
          required:
            - email
          properties:
            email:
              type: string 
        - type: object
          description: phone
          required:
            - phone
          properties:
            phone:
              type: string 
    
    PartyAddress:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
          nullable: true
        zip:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
    
    PartyProperty:
      type: object
      properties:
        propertyId:
          type: string
        propertyType:
          type: string
          enum: [OWNED,RENTED,BROKERED]
        propertyStatus:
          type: string
          enum: [ACTIVE,INACTIVE,INPROGRESS]  
        startDate:
          type: string
          nullable: true
          format: date
        endDate:
          type: string
          nullable: true
          format: date
        
    CreatePartyRequest:
      allOf:
        - $ref: '#/components/schemas/PartyDemographics'
        - $ref: '#/components/schemas/PartyContact'
          
    CreatePartyResponse:  
      type: object
      properties:
        partyID:
          type: string
          description: party ID created
      
    SearchPartyRequest:
      oneOf:
        - type: object
          properties:
            firstName:
              type: string
            lastName:
              type: string
            dob:
              type: string 
              format: date   
        - type: object
          properties:
            email:
              type: string
              format: email
        - type: object
          properties:
            phone:
              type: string               
        
          
    SearchPartyResponse:  
      type: array
      items:
        $ref: '#/components/schemas/PartyResponse'
      
          
    ExecuteException:
      type: object
      properties:
        code:
          type: string
          description: The code identifying the type of error
        message:
          type: string
          description: The error message
